=== apache/servicemix3/servicemix-schemas/src/main/xsd/jbi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://java.sun.com/xml/ns/jbi" xmlns:this="http://java.sun.com/xml/ns/jbi">
  <xs:element name="jbi">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="this:component"/>
        <xs:element ref="this:service-assembly"/>
        <xs:group ref="this:shared-library"/>
        <xs:element ref="this:services"/>
      </xs:choice>
      <xs:attribute name="version" use="required" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="component">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="this:identification"/>
        <xs:element ref="this:component-class-name"/>
        <xs:element ref="this:component-class-path"/>
        <xs:element ref="this:bootstrap-class-name"/>
        <xs:element ref="this:bootstrap-class-path"/>
        <xs:group minOccurs="0" maxOccurs="unbounded" ref="this:shared-library-list"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:any namespace="##other" processContents="skip"/>
          <xs:any namespace="##local" processContents="skip"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="service-engine"/>
            <xs:enumeration value="binding-component"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="component-class-loader-delegation">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="parent-first"/>
            <xs:enumeration value="self-first"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="bootstrap-class-loader-delegation">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="parent-first"/>
            <xs:enumeration value="self-first"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="component-class-name">
    <xs:complexType mixed="true">
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="component-class-path" type="this:class-path"/>
  <xs:element name="bootstrap-class-name" type="xs:string"/>
  <xs:element name="bootstrap-class-path" type="this:class-path"/>
  <xs:group name="shared-library">
    <xs:sequence>
      <xs:element name="shared-library">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="this:identification"/>
            <xs:element ref="this:shared-library-class-path"/>
          </xs:sequence>
          <xs:attribute name="class-loader-delegation">
            <xs:simpleType>
              <xs:restriction base="xs:token">
                <xs:enumeration value="parent-first"/>
                <xs:enumeration value="self-first"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="version"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:group>
  <xs:element name="shared-library-class-path" type="this:class-path"/>
  <xs:group name="shared-library-list">
    <xs:sequence>
      <xs:element name="shared-library">
        <xs:complexType mixed="true">
          <xs:attribute name="version"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:group>
  <xs:element name="service-assembly">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="this:identification"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="this:service-unit"/>
        <xs:element minOccurs="0" ref="this:connections"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:any namespace="##other" processContents="skip"/>
          <xs:any namespace="##local" processContents="skip"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="service-unit">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="this:identification"/>
        <xs:element ref="this:target"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:any namespace="##other" processContents="skip"/>
          <xs:any namespace="##local" processContents="skip"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="target">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="this:artifacts-zip"/>
        <xs:element ref="this:component-name"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="artifacts-zip" type="xs:string"/>
  <xs:element name="component-name" type="xs:string"/>
  <xs:element name="identification">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="this:name"/>
        <xs:element ref="this:description"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:any namespace="##other" processContents="skip"/>
          <xs:any namespace="##local" processContents="skip"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:complexType name="class-path">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" ref="this:path-element"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="path-element" type="xs:string"/>
  <xs:element name="connections">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="this:connection"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:any namespace="##other" processContents="skip"/>
          <xs:any namespace="##local" processContents="skip"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="connection">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="this:consumer"/>
        <xs:element ref="this:provider"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="consumer">
    <xs:complexType>
      <xs:attribute name="interface-name" type="xs:QName"/>
      <xs:attribute name="service-name" type="xs:QName"/>
      <xs:attribute name="endpoint-name"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="provider">
    <xs:complexType>
      <xs:attribute name="service-name" use="required" type="xs:QName"/>
      <xs:attribute name="endpoint-name" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="services">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="this:provides"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="this:consumes"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:any namespace="##other" processContents="skip"/>
          <xs:any namespace="##local" processContents="skip"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="binding-component" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="provides">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:any namespace="##other" processContents="skip"/>
        <xs:any namespace="##local" processContents="skip"/>
      </xs:choice>
      <xs:attribute name="interface-name" use="required" type="xs:QName"/>
      <xs:attribute name="service-name" use="required" type="xs:QName"/>
      <xs:attribute name="endpoint-name" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="consumes">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:any namespace="##other" processContents="skip"/>
        <xs:any namespace="##local" processContents="skip"/>
      </xs:choice>
      <xs:attribute name="interface-name" use="required" type="xs:QName"/>
      <xs:attribute name="service-name" type="xs:QName"/>
      <xs:attribute name="endpoint-name"/>
      <xs:attribute name="link-type">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="standard"/>
            <xs:enumeration value="hard"/>
            <xs:enumeration value="soft"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== apache/servicemix3/servicemix-core/src/test/resources/org/apache/servicemix/jbi/deployment/SharedLibrary.xml
<?xml version="1.0"?>
<!-- jbi.xml file for a sample shared library. -->
<jbi version="1.0" xmlns="http://java.sun.com/xml/ns/jbi"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/jbi ./jbi.xsd">

	<!-- identification information about this shared library-->
	<shared-library>
		<identification>
			<name>TestSharedLibrary</name>
			<description>This is a test shared library.</description>
		</identification>
		<shared-library-class-path>
			<path-element>.</path-element>
			<path-element>test.jar</path-element>
		</shared-library-class-path>
	</shared-library>
</jbi>
